CREATE DATABASE web_day6;


USE web_day6;

CREATE TABLE STUDENT(STUDENT_ID INT NOT NULL AUTO_INCREMENT, STUDENT_NAME VARCHAR(50) NOT NULL, STUDENT_ADDRESS VARCHAR(100) NOT NULL, PRIMARY KEY ( STUDENT_ID ));